Revert "Sync master-priv with public sunnypilot:master"

diff --git a/.github/workflows/selfdrive_tests.yaml b/.github/workflows/selfdrive_tests.yaml
--- a/.github/workflows/selfdrive_tests.yaml
+++ b/.github/workflows/selfdrive_tests.yaml
@@ -16,7 +16,8 @@ env:
   CL_BASE_IMAGE: openpilot-base-cl
   AZURE_TOKEN: ${{ secrets.AZURE_COMMADATACI_OPENPILOTCI_TOKEN }}
 
-  DOCKER_LOGIN: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
+  DOCKER_GHCR_LOGIN: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
+  DOCKER_HUB_LOGIN: docker login -u adeebshihadeh -p ${{ secrets.DOCKER_HUB_PAT }}
   BUILD: selfdrive/test/docker_build.sh base
 
   RUN: docker run --shm-size 1G -v $PWD:/tmp/openpilot -w /tmp/openpilot -e PYTHONWARNINGS=error -e FILEREADER_CACHE=1 -e PYTHONPATH=/tmp/openpilot -e NUM_JOBS -e JOB_ID -e GITHUB_ACTION -e GITHUB_REF -e GITHUB_HEAD_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_RUN_ID -v $GITHUB_WORKSPACE/.ci_cache/scons_cache:/tmp/scons_cache -v $GITHUB_WORKSPACE/.ci_cache/comma_download_cache:/tmp/comma_download_cache -v $GITHUB_WORKSPACE/.ci_cache/openpilot_cache:/tmp/openpilot_cache $BASE_IMAGE /bin/sh -c
@@ -38,7 +39,6 @@ jobs:
     - uses: actions/checkout@v3
       with:
         submodules: true
-    - run: git lfs pull
     - name: Build devel
       timeout-minutes: 1
       run: TARGET_DIR=$STRIPPED_DIR release/build_devel.sh
@@ -66,31 +66,123 @@ jobs:
         cp pyproject.toml $STRIPPED_DIR
         cp poetry.lock $STRIPPED_DIR
         cd $STRIPPED_DIR
-        ${{ env.RUN }} "unset PYTHONWARNINGS && SKIP=check-added-large-files pre-commit run --all"
+        ${{ env.RUN }} "unset PYTHONWARNINGS && pre-commit run --all"
 
   build:
     strategy:
       matrix:
-        arch: ${{ fromJson(
-           ((github.repository == 'commaai/openpilot') &&
-              ((github.event_name != 'pull_request') || 
-               (github.event.pull_request.head.repo.full_name == 'commaai/openpilot'))) && '["x86_64", "aarch64"]' || '["x86_64"]' ) }}
+        arch: ${{ fromJson( (github.repository == 'commaai/openpilot') && '["x86_64", "aarch64"]' || '["x86_64"]' ) }}
     runs-on: ${{ (matrix.arch == 'aarch64') && 'buildjet-2vcpu-ubuntu-2204-arm' || 'ubuntu-20.04' }}
     steps:
     - uses: actions/checkout@v3
       with:
         submodules: true
+    # login only on arm machines, due to buildjet rate limits
+    - name: Setup docker
+      if: contains(runner.name, 'buildjet')
+      run: |
+        $DOCKER_HUB_LOGIN
     - uses: ./.github/workflows/setup-with-retry
       with:
-        docker_hub_pat: ${{ secrets.DOCKER_HUB_PAT }}
         cache_key_prefix: scons_${{ matrix.arch }}
     - uses: ./.github/workflows/compile-openpilot
       timeout-minutes: ${{ ((steps.restore-scons-cache.outputs.cache-hit == 'true') && 15 || 30) }} # allow more time when we missed the scons cache
       with:
         cache_key_prefix: scons_${{ matrix.arch }}
 
+  build_mac:
+    name: build macos
+    runs-on: macos-latest
+    steps:
+    - uses: actions/checkout@v3
+      with:
+        submodules: true
+    - name: Determine pre-existing Homebrew packages
+      if: steps.dependency-cache.outputs.cache-hit != 'true'
+      run: |
+        echo 'EXISTING_CELLAR<<EOF' >> $GITHUB_ENV
+        brew list --formula -1 >> $GITHUB_ENV
+        echo 'EOF' >> $GITHUB_ENV
+    - name: Restore scons cache
+      id: scons-restore-cache
+      uses: actions/cache/restore@v3
+      with:
+        path: /tmp/scons_cache
+        key: macos_scons-${{ github.sha }}
+        restore-keys: macos_scons-
+    - name: Cache dependencies
+      id: dependency-cache
+      uses: actions/cache@v3
+      with:
+        path: |
+          .env
+          .venv
+          ~/github_brew_cache_entries.txt
+          ~/.pyenv
+          ~/Library/Caches/pypoetry
+          /usr/local/Cellar
+          /usr/local/opt
+          /usr/local/Caskroom/gcc-arm-*
+          /opt/homebrew/Cellar
+          /opt/homebrew/opt
+          /opt/homebrew/Caskroom/gcc-arm-*
+          /Applications/ArmGNUToolchain/*/*/*
+        key: macos_deps-${{ hashFiles('tools/mac_setup.sh', 'tools/install_python_dependencies.sh', 'poetry.lock') }}
+        restore-keys: macos_deps-
+    - name: Brew link restored dependencies
+      run: |
+        if [ -f ~/github_brew_cache_entries.txt ]; then
+          brew link --force --overwrite $(cat ~/github_brew_cache_entries.txt) # `--force` for keg-only packages
+          if [ -d /Applications/ArmGNUToolchain ]; then # link gcc-arm-embedded manually
+            GCC_TOOLCHAIN="$(echo /Applications/ArmGNUToolchain/**/**/bin)"
+            echo "$GCC_TOOLCHAIN" >> $GITHUB_PATH
+          fi
+        else
+          echo "Cache entries not found"
+        fi
+    - name: Install dependencies
+      if: steps.dependency-cache.outputs.cache-hit != 'true'
+      run: ./tools/mac_setup.sh
+      env:
+        # package install has DeprecationWarnings
+        PYTHONWARNINGS: default
+    - name: Build openpilot
+      run: |
+        eval "$(pyenv init --path)"
+        poetry run scons -j$(nproc)
+    - name: Run tests
+      run: |
+        eval "$(pyenv init --path)"
+        poetry run tools/plotjuggler/test_plotjuggler.py
+    - name: Pre Cache - Cleanup scons cache
+      if: github.ref == 'refs/heads/master'
+      run: |
+        rm -rf /tmp/scons_cache/*
+        eval "$(pyenv init --path)"
+        poetry run scons -j$(nproc) --cache-populate
+    - name: Save scons cache
+      id: scons-save-cache
+      uses: actions/cache/save@v3
+      if: github.ref == 'refs/heads/master'
+      with:
+        path: /tmp/scons_cache
+        key: macos_scons-${{ github.sha }}
+    - name: Pre Cache - Remove pre-existing Homebrew packages
+      if: steps.dependency-cache.outputs.cache-hit != 'true'
+      run: |
+        new_cellar=$(brew list --formula -1)
+        exceptions="zstd lz4 xz" # caching step needs zstd
+        comm -12 <(echo "$EXISTING_CELLAR") <(echo "$new_cellar") | while read pkg; do
+          if [[ " $exceptions " != *" $pkg "* ]]; then
+            rm -rf "$(brew --cellar)/$pkg"
+          fi
+        done
+        comm -13 <(echo "$EXISTING_CELLAR") <(echo "$new_cellar") | tee ~/github_brew_cache_entries.txt
+        # .fseventsd directory causes permission errors in dep caching step
+        # its used by the system to observe changes within the directory - toolchain works without it, just remove it
+        sudo rm -rf /Applications/ArmGNUToolchain/*/*/.fseventsd
+
   docker_push:
-    name: docker push
     strategy:
       matrix:
         arch: ${{ fromJson( (github.repository == 'commaai/openpilot') && '["x86_64", "aarch64"]' || '["x86_64"]' ) }}
@@ -104,10 +196,15 @@ jobs:
       run: |
         echo "PUSH_IMAGE=true" >> "$GITHUB_ENV"
         echo "TARGET_ARCHITECTURE=${{ matrix.arch }}" >> "$GITHUB_ENV"
-        $DOCKER_LOGIN
+        $DOCKER_GHCR_LOGIN
+    # login only on arm machines, due to buildjet rate limits
+    - name: Additional setup for buildjet
+      if: contains(runner.name, 'buildjet')
+      run: |
+        $DOCKER_HUB_LOGIN
     - uses: ./.github/workflows/setup-with-retry
       with:
-        docker_hub_pat: ${{ secrets.DOCKER_HUB_PAT }}
+        git-lfs: false
     - name: Build and push CL Docker image
       if: matrix.arch == 'x86_64'
       run: |
@@ -125,7 +222,7 @@ jobs:
         submodules: false
     - name: Setup docker
       run: |
-        $DOCKER_LOGIN
+        $DOCKER_GHCR_LOGIN
     - name: Merge x64 and arm64 tags
       run: |
         export PUSH_IMAGE=true
@@ -138,7 +235,8 @@ jobs:
     - uses: actions/checkout@v3
       with:
         submodules: true
-    - uses: ./.github/workflows/setup-with-retry
+    - name: Build Docker image
+      run: eval "$BUILD"
     - name: pre-commit
       timeout-minutes: 4
       run: ${{ env.RUN }} "unset PYTHONWARNINGS && pre-commit run --all"
@@ -173,9 +271,10 @@ jobs:
       timeout-minutes: ${{ ((steps.restore-scons-cache.outputs.cache-hit == 'true') && 10 || 30) }} # allow more time when we missed the scons cache
       run: ${{ env.RUN }} "scons -j$(nproc)"
     - name: Run unit tests
-      timeout-minutes: 15
+      timeout-minutes: 40
       run: |
-        ${{ env.RUN }} "$PYTEST -n auto --dist=loadscope --timeout 30 -o cpp_files=test_* -m 'not slow' && \
+        ${{ env.RUN }} "export SKIP_LONG_TESTS=1 && \
+                        $PYTEST -n auto --dist=loadscope --timeout 30 -o cpp_files=test_* && \
                         ./selfdrive/ui/tests/create_test_translations.sh && \
                         QT_QPA_PLATFORM=offscreen ./selfdrive/ui/tests/test_translations && \
                         ./selfdrive/ui/tests/test_translations.py && \
@@ -186,16 +285,12 @@ jobs:
 
   process_replay:
     name: process replay
-    runs-on: ${{ ((github.repository == 'commaai/openpilot') &&
-                   ((github.event_name != 'pull_request') || 
-                    (github.event.pull_request.head.repo.full_name == 'commaai/openpilot'))) && 'buildjet-8vcpu-ubuntu-2004' || 'ubuntu-20.04' }}
+    runs-on: ${{ ((github.event.pull_request.head.repo.full_name == 'commaai/openpilot') || (github.repository == 'commaai/openpilot')) && 'buildjet-8vcpu-ubuntu-2004' || 'ubuntu-20.04' }}
     steps:
     - uses: actions/checkout@v3
       with:
         submodules: true
     - uses: ./.github/workflows/setup-with-retry
-      with:
-        docker_hub_pat: ${{ secrets.DOCKER_HUB_PAT }}
     - name: Cache test routes
       id: dependency-cache
       uses: actions/cache@v3
@@ -215,7 +310,7 @@ jobs:
       id: print-diff
       if: always()
       run: cat selfdrive/test/process_replay/diff.txt
-    - uses: actions/upload-artifact@v3
+    - uses: actions/upload-artifact@v2
       if: always()
       continue-on-error: true
       with:
@@ -227,33 +322,6 @@ jobs:
         ${{ env.RUN }} "unset PYTHONWARNINGS && CI=1 AZURE_TOKEN='$AZURE_TOKEN' python selfdrive/test/process_replay/test_processes.py -j$(nproc) --upload-only"
     - name: "Upload coverage to Codecov"
       uses: codecov/codecov-action@v3
-
-  regen:
-    name: regen
-    runs-on: 'ubuntu-20.04'
-    steps: 
-    - uses: actions/checkout@v3
-      with:
-        submodules: true
-    - uses: ./.github/workflows/setup-with-retry
-    - name: Cache test routes
-      id: dependency-cache
-      uses: actions/cache@v3
-      with:
-        path: .ci_cache/comma_download_cache
-        key: regen-${{ hashFiles('.github/workflows/selfdrive_tests.yaml', 'selfdrive/test/process_replay/test_regen.py') }}
-    - name: Build base Docker image
-      run: eval "$BUILD"
-    - name: Build Docker image
-      run: eval "$BUILD_CL"
-    - name: Build openpilot
-      run: |
-        ${{ env.RUN }} "scons -j$(nproc)"
-    - name: Run regen
-      timeout-minutes: 30
-      run: |
-        ${{ env.RUN_CL }} "ONNXCPU=1 $PYTEST -n auto --dist=loadscope selfdrive/test/process_replay/test_regen.py && \
-                           chmod -R 777 /tmp/comma_download_cache"
 
   test_modeld:
     name: model tests
@@ -327,7 +395,6 @@ jobs:
         with:
           submodules: true
           ref: ${{ github.event.pull_request.base.ref }}
-      - run: git lfs pull
       - uses: ./.github/workflows/setup-with-retry
       - name: Get base car info
         run: |
@@ -337,7 +404,6 @@ jobs:
         with:
           submodules: true
           path: current
-      - run: cd current && git lfs pull
       - name: Save car docs diff
         id: save_diff
         run: |
